#!/usr/bin/env bash
# configures the server to listening on port 80 of all servers active for IPv4 IPs
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart